// Wikipedia Commons SVG/PNG logo URLs for car brands
// Source: https://commons.wikimedia.org
export const brandData: Record<string, { domain: string; wikiLogo: string }> = {
  alfaromeo: { domain: "alfaromeo.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/0/03/Alfa_Romeo_Badge.svg" },
  audi: { domain: "audi.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Audi-Logo_2016.svg" },
  bmw: { domain: "bmw.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/4/44/BMW.svg" },
  citroen: { domain: "citroen.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Citroen_2009_logo.svg" },
  dacia: { domain: "dacia.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/4/41/Dacia-Logo-2021.svg" },
  ds: { domain: "dsautomobiles.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/5/51/DS_Automobiles_logo.svg" },
  fiat: { domain: "fiat.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/2/27/Fiat_Automobiles_logo.svg" },
  ford: { domain: "ford.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Ford_Motor_Company_Logo.svg" },
  honda: { domain: "honda.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/7/76/Honda_logo.svg" },
  hyundai: { domain: "hyundai.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Hyundai_Motor_Company_logo.svg" },
  jaguar: { domain: "jaguar.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/5/50/Jaguar_Cars_logo.svg" },
  jeep: { domain: "jeep.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Jeep_logo.svg" },
  kia: { domain: "kia.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/1/13/Kia-logo.png" },
  "land-rover": { domain: "landrover.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Land_Rover_company_logo.png" },
  lexus: { domain: "lexus.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Lexus_division_emblem.svg" },
  maserati: { domain: "maserati.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/1/14/Maserati_logo.svg" },
  mazda: { domain: "mazda.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/8/85/Mazda_logo_with_wing.svg" },
  mercedes: { domain: "mercedes-benz.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/9/90/Mercedes-Benz_combined_logo_-_2010.svg" },
  mg: { domain: "mg.co.uk", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/7/71/MG_Motor_logo.svg" },
  mini: { domain: "mini.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Mini_Cooper_logo.svg" },
  nissan: { domain: "nissan.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Nissan_logo_2020.svg" },
  opel: { domain: "opel.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/1/11/Opel_logo.svg" },
  peugeot: { domain: "peugeot.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/8/83/Peugeot_2010_logo.svg" },
  porsche: { domain: "porsche.com", wikiLogo: "/logos/coc/porsche-6.svg" },
  renault: { domain: "renault.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/4/49/Renault_2009_logo.svg" },
  seat: { domain: "seat.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/8/82/SEAT_Logo.svg" },
  skoda: { domain: "skoda-auto.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/5/55/Skoda_Auto_logo.svg" },
  smart: { domain: "smart.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Smart_logo.svg" },
  ssangyong: { domain: "ssangyong.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/c/c9/SsangYong_Motor_Company_logo.svg" },
  subaru: { domain: "subaru.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Subaru_logo.svg" },
  suzuki: { domain: "suzuki.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/b/be/Suzuki_logo.svg" },
  tesla: { domain: "tesla.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Tesla_Motors.svg" },
  toyota: { domain: "toyota.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Toyota_logo_silver.svg" },
  volkswagen: { domain: "volkswagen.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Volkswagen_logo_2019.svg" },
  volvo: { domain: "volvo.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Volvo_logo.svg" },
  cupra: { domain: "cupraofficial.com", wikiLogo: "/logos/coc/cupra.svg" },
  byd: { domain: "byd.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/0/00/BYD_Auto_logo.svg" },
  chery: { domain: "cheryinternational.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/0/00/Chery_logo.svg" },
  neta: { domain: "netaauto.com", wikiLogo: "https://upload.wikimedia.org/wikipedia/commons/8/8d/NETA_Auto_logo.svg" },
};
